version: '3.9'

networks:
  envybox-test:

services:
  envybox-php:
    build:
      context: .
      dockerfile: ./_docker/php.dockerfile
    container_name: envybox-php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./_docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - envybox-test

  admin-nginx:
    image: nginx:alpine
    container_name: envybox-nginx
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - "8056:80"
    volumes:
      - .:/var/www
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - envybox-php
    networks:
      - envybox-test

  envybox-db:
    image: mariadb:10.10
    ports:
      - 3398:3306
    volumes:
      - ./_docker/db/dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: envibox
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - envybox-test

  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - envybox-db:envybox-db
    restart: always
    ports:
      - "3399:80"
    environment:
      PMA_HOST: envybox-db
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    depends_on:
      - envybox-db
    networks:
      - envybox-test

